---
title: "課?<a0>?練習模<e7><89><88>"
author: "Hannah"
date: "2020-12-01"
output: output_format
params:
  id: "410782022"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
myFavoriteSinger <- list("A","B","c")
myFavoriteSinger[c(1,3)] <- NULL
myFavoriteSinger

```
```{r}
a <- c(10, 12, 34)
b <- c(7, -13, 29)
```
```{r}
a+b
a-b
a*b
a/b
a%%b
a^b
```
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
print(sequenceNums)

sequenceNums %% 2 # 餘數為1則是奇數，0則是偶數
```
```{r}
3**-1
```
```{r}
5*c(1,3,4)+7
# 其實是
c(5)*c(1,3,4)+c(7)

## 對向量5，向量7進行recycle:
c(5,5,5)*c(1,3,4)+c(7,7,7)
## Recycle等長後才進行elementwise operation:
c(5*1+7, 5*3+7, 5*4+7)
```
```{r}
# 狀況一: 堆疊一定倍數剛好一樣長
c(2,3)/c(-2,-13,10,22)
c(2,3,2,3)/c(-2,-13,10,22)
```
```{r}
# 狀況二: 倍數堆疊一定會超過，只好截斷
c(2,3)/c(-2,-13,10)
c(2,3,2)/c(-2,-13,10)
```
```{r}
paste0(
  c("他叫","我叫"), c("小明","小美","大雄")
)
```
```{r}
threeFiles <- paste0("file",1:3, ".csv")
file.create(c("file1.csv","file2.csv","file3.csv"))
```
```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```
```{r}
tr_example <- purrr::transpose(example)
str(tr_example)
```
```{r}
df_example <- as.data.frame(example)
```
```{r}
example2 <- 
  list(
    name=c("John", "Mary"),
    height=list(178, 168), # not atomic vector
    weight=c(88, 56, 70) # not the same length as other elements
  )
as.data.frame(example2)
```
```{r}
# 使用list的工具
df_example$name[c(1,4)]

# 使用data frame的延伸工具`[.row, .column]`
df_example[c(1,4), "name"]
```
```{r}
df_example[c(1,4), c("name","residence")]

# 只使用list工具
list(
  name=df_example$name[c(1,4)],
  residence=df_example$residence[c(1,4)]
)
```
```{r}
example$name[c(T, F, T, F)]
```
```{r}
str(example[c("name","height")])

pick_above170 <- example$height >= 170
pick_above170
example$name[pick_above170]
```
```{r}
pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example[["name"]][pick_after98]
```
```{r}
example$allowance <- 
  ordered(example$allowance)
```
```{r}
example$allowance <-
  factor(
    example$allowance,
    levels=c("0-1000", "1001-2000", "2000+"),
    ordered = T # 設定為可排序factor
  )
```
```{r}
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```



